### PR TITLE
Added function to calculate surface area

### PR DESCRIPTION
**Pull request by redwildfire13**
Added function to calculate surface area and converted Vertexes to Vector3 and Triangles.
Included prototype functions for basic Vector3 math.

### CODE REVIEW

**Comment by johannesboyne** [comment]
Hi @redwildfire13 thanks a lot for the contribution. Do you mind adding a little test for the calculation of the surface area?

**Comment by redwildfire13** [comment]
I just committed the box I used to verify, but I'm not sure how to add it to this pull request so I've attached it here (zipped stl file).
[box_2x3x4.zip](https://github.com/johannesboyne/node-stl/files/454326/box_2x3x4.zip)

**Comment by redwildfire13** [comment]
Ok, I think I got it. I've never used parse.js before so I hope its right!

**Comment by johannesboyne** [comment]
@redwildfire13 I'm very sorry, I just forget your PR. Is this still relevant?

**Comment by redwildfire13** [comment]
Yes, I believe it still is.

**Pull request merged**
